include_recipe "../cookbooks/sshd/default.rb"
include_recipe "../cookbooks/vim/default.rb"
include_recipe "../cookbooks/wget/default.rb"
include_recipe "../cookbooks/firewalld/default.rb"
include_recipe "../cookbooks/mysql/default.rb"
include_recipe "../cookbooks/nginx/default.rb"
include_recipe "../cookbooks/redis/default.rb"
